### ISSUE TITLE
🚀 Feature:  why don't show up when i search "What words have a gematria of 1444?" ויוצא ישראל מתוכם כי לעולם חסדו

### ISSUE THREAD

**Issue by a7826489** [torahcalc/torahcalc#191]
### Description

![Screenshot 2024-09-19 140916](https://github.com/user-attachments/assets/5bf26e00-bc1e-4929-8fa7-fbb9a2fbb7be)

**Comment by DenverCoder1** [comment]
I will look into it, it seems some verses were skipped in the [calculation](https://pub.microbin.eu/upload/bat-worm-ant) process.

**Comment by DenverCoder1** [comment]
![image](https://github.com/user-attachments/assets/5502c645-e9cf-46da-9070-f47f701b1d9f)

**Comment by a7826489** [comment]
thanks
i like vary much your services
i just want to know more abut u mission and goal
