### ISSUE TITLE
🐛 Bug: Remove "0 minutes" or "0 chalakim" from molad text

### ISSUE THREAD

**Issue by DenverCoder1** [torahcalc/torahcalc#22]
### Description

It's not relevant to show when it is 0 minutes or 0 chalakim after the hour so it could be hidden

`Friday, Sep. 15, 2023, 5:49 am and 0 chalakim` => `Friday, Sep. 15, 2023, 5:49 am`
`Friday morning, 49 minutes and 0 chalakim after 5:00 am` => `Friday morning, 49 minutes after 5:00 am`
`29th of Elul, 5783, 5:49 am and 0 chalakim` => `29th of Elul, 5783, 5:49 am`

`Saturday morning, 0 minutes and 7 chalakim after 12:00 am` => `Saturday morning, 7 chalakim after 12:00 am`

### Steps to reproduce

https://torahcalc.vercel.app/api/molad?year=5784&month=7

https://torahcalc.vercel.app/api/molad?year=5771&month=13

**Comment by iakgoog** [comment]
@DenverCoder1, Please assign me.

**Comment by DenverCoder1** [comment]
Sounds great! Feel free to let me know if you have any questions!
