### ISSUE TITLE
🐛 Bug: The menu does not close automatically on mobile

### ISSUE THREAD

**Issue by DenverCoder1** [torahcalc/torahcalc#37]
### Description

Make sure the mobile menu collapses when the page is changed

### Steps to reproduce

Open on a mobile device or narrow browser window
Click the menu icon to expand the menu
Select a page to switch to
Observe that the menu stays open

### Screenshots

![image](https://github.com/torahcalc/torahcalc/assets/20955511/b575e4b9-ca2d-45ea-b6ab-28b234b637f9)

**Comment by iakgoog** [comment]
@DenverCoder1, Please assign me.

**Comment by DenverCoder1** [comment]
@iakgoog Thanks, if you have any questions, don't hesitate to ask!

**Comment by danielkhayat16** [comment]
@DenverCoder1 I think I found a simple solution to fix this issue, can I just commit it and wait for your review?

**Comment by DenverCoder1** [comment]
@danielkhayat16 Normally when there's already an assignee and/or PR open, it's recommended to discuss it first with whoever is already working on it in order that someone's work doesn't get rejected.

I do see in the commits think that your solution does appear to work and is simpler than the current proposed solution.

If @iakgoog is okay with you opening a PR to propose your solution, then it's fine. Otherwise, if they prefer, they can apply your fix to their PR and co-author you on the commit so you get credit for contributing.

**Comment by danielkhayat16** [comment]
Okay, Sorry this is my first time contributing. I take note of your advices! I am fine with being co author

**Comment by DenverCoder1** [comment]
@danielkhayat16 No problem, happy to have you helping here. I'll give a few days for iakgoog to comment and after that we'll decide how we are moving forward.

**Comment by iakgoog** [comment]
Sure @danielkhayat16  you can take this issue.

**Comment by DenverCoder1** [comment]
Thanks for the followup. @danielkhayat16 Feel free to open a PR, let me know if you have any questions.
